server:
  port: 8002


spring:
  application:
    name: con
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

# 开启熔断
feign:
  hystrix:
    enabled: true

hystrix:
  metrics:
    polling-interval-ms: 1000